version: '2'
services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/app
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
