version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
  worker:
    device_requests:
      - capabilities:
        - "gpu"    
    build:
      context: .
      dockerfile: worker.Dockerfile
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:latest
    env_file: .env
  redis:
    image: redis:alpine
    command: redis-server --save ""  
    volumes:
      - "./redis-data:/data"
